version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'ðŸ†™ action'
    labels:
      - 'github-action :robot:'

  - package-ecosystem: 'terraform'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'ðŸ†™ tf'
      include: 'scope'
    labels:
      - 'dependency :robot:'
